version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  pattern-classifier:
    build: .
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - COLLECTION_NAME=pattern_index
      - MODEL_NAME=all-MiniLM-L6-v2
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      qdrant:
        condition: service_healthy
    volumes:
      - ./cold_path/patterns:/app/cold_path/patterns:ro
    restart: unless-stopped
    
  # Build index using Python cold path (run once)
  index-builder:
    build: .
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - COLLECTION_NAME=pattern_index
    depends_on:
      qdrant:
        condition: service_healthy
    volumes:
      - ./cold_path/patterns:/app/cold_path/patterns:ro
    command: poetry run python -m cold_path.tools.build_pattern_index --overwrite
    restart: "no"

volumes:
  qdrant_storage: 